---
# Source: orientdb/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: orientdb-incubator-secret
  labels:
    app: orientdb
    release: orientdb-incubator
data:
  root-password: "elg5dm55dkxsVQ=="

---
# Source: orientdb/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: orientdb-incubator-configmap
data:
  default-distributed-db-config.json: |-
    {
      "autoDeploy": true,
      "executionMode": "undefined",
      "readQuorum": 1,
      "writeQuorum": "majority",
      "readYourWrites": true,
      "newNodeStrategy": "static",
      "servers": { "*": "master" },
      "clusters": {
        "internal": {},
        "*": {
          "servers": ["<NEW_NODE>"]
        }
      }
    }

  hazelcast.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- ~ Copyright (c) 2008-2012, Hazel Bilisim Ltd. All Rights Reserved. ~
      ~ Licensed under the Apache License, Version 2.0 (the "License"); ~ you may
      not use this file except in compliance with the License. ~ You may obtain
      a copy of the License at ~ ~ http://www.apache.org/licenses/LICENSE-2.0 ~
      ~ Unless required by applicable law or agreed to in writing, software ~ distributed
      under the License is distributed on an "AS IS" BASIS, ~ WITHOUT WARRANTIES
      OR CONDITIONS OF ANY KIND, either express or implied. ~ See the License for
      the specific language governing permissions and ~ limitations under the License. -->

    <hazelcast
            xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.3.xsd"
            xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <group>
            <!-- From values.yaml -->
            <name>orientdb</name>
            <password>orientdb</password>
        </group>
        <properties>
            <property name="hazelcast.phone.home.enabled">false</property>
            <property name="hazelcast.mancenter.enabled">false</property>
            <property name="hazelcast.memcache.enabled">false</property>
            <property name="hazelcast.rest.enabled">false</property>
            <property name="hazelcast.wait.seconds.before.join">5</property>
            <property name="hazelcast.operation.thread.count">1</property>
            <property name="hazelcast.io.thread.count">1</property>
            <property name="hazelcast.operation.generic.thread.count">1</property>
            <property name="hazelcast.client.event.thread.count">1</property>
            <property name="hazelcast.event.thread.count">1</property>
            <property name="hazelcast.heartbeat.interval.seconds">5</property>
            <property name="hazelcast.max.no.heartbeat.seconds">30</property>
            <property name="hazelcast.merge.next.run.delay.seconds">15</property>
        </properties>
        <network>
            <port auto-increment="true">2434</port>
            <join>
                <multicast enabled="false">
                    <multicast-group>235.1.1.1</multicast-group>
                    <multicast-port>2434</multicast-port>
                </multicast>
                <tcp-ip enabled="true">
                <!-- From values.yaml -->
                    <member>orientdb-incubator-0.orientdb-incubator-headless.default.svc.cluster.local</member>
                    <member>orientdb-incubator-1.orientdb-incubator-headless.default.svc.cluster.local</member>
                    <member>orientdb-incubator-2.orientdb-incubator-headless.default.svc.cluster.local</member>
                </tcp-ip>
            </join>
        </network>
        <executor-service>
            <pool-size>16</pool-size>
        </executor-service>
    </hazelcast>

---
# Source: orientdb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: orientdb-incubator-headless
  labels:
    app: orientdb
    release: orientdb-incubator
spec:
  type: ClusterIP
  ports:
    - port: 2480
      targetPort: http
      name: http
    - port: 2434
      targetPort: hazelcast
      name: hazelcast
    - port: 2424
      targetPort: binary
      name: binary
    - port: 8182
      targetPort: gremlin
      name: gremlin
  clusterIP: None
  selector:
    app: orientdb
    release: orientdb-incubator
---
apiVersion: v1
kind: Service
metadata:
  name: orientdb-incubator-svc
  labels:
    app: orientdb
    release: orientdb-incubator
spec:
  type: ClusterIP
  ports:
    - port: 2480
      targetPort: http
      name: http
    - port: 2434
      targetPort: hazelcast
      name: hazelcast
    - port: 2424
      targetPort: binary
      name: binary
    - port: 8182
      targetPort: gremlin
      name: gremlin
  selector:
    app: orientdb
    release: orientdb-incubator

---
# Source: orientdb/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orientdb-incubator
  labels:
    app: orientdb
    release: orientdb-incubator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orientdb
      release: orientdb-incubator
  serviceName: orientdb-incubator-headless
  template:
    metadata:
      labels:
        app: orientdb
        release: orientdb-incubator
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        # orientdb-server-config.xml is an executable file while kubernetes mounts
        # configmaps as read-only (since 1.94). This is a workaround to mount it as
        # configmap first and then copy it over to its final location
      - name: "fix-orientdb-server-config"
        image: "busybox" # Needs to be changed
        imagePullPolicy: IfNotPresent
        command: [ "sh", "-c", "cp  /configmap/* /config" ]
        volumeMounts:
        - name: orientdb-configmap-vol
          mountPath: /configmap
        - name: orientdb-config-vol
          mountPath: /config
      containers:
      - name: orientdb
        image: "orientdb:3.0.13"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 2480
            name: http
          - containerPort: 2434
            name: hazelcast
          - containerPort: 2424
            name: binary
          - containerPort: 8182
            name: gremlin
        env:
          - name: ORIENTDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: orientdb-incubator-secret
                key: root-password
          - name: ORIENTDB_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: orientdb-config-vol
            mountPath: /orientdb/config/hazelcast.xml
            subPath: hazelcast.xml
          - name: orientdb-config-vol
            mountPath: /orientdb/config/default-distributed-db-config.json
            subPath: default-distributed-db-config.json
          - name: storage
            mountPath: /orientdb/databases
          - name: backup
            mountPath: /orientdb/backup
        readinessProbe:
          tcpSocket:
            port: http
        livenessProbe:
          tcpSocket:
            port: http
        command: ["dserver.sh"]
        resources:
            limits:
              cpu: 2000m
              memory: 8Gi
            requests:
              cpu: 500m
              memory: 2Gi

      volumes:
        - name: orientdb-configmap-vol
          configMap:
            name: orientdb-incubator-configmap
        - name: orientdb-config-vol
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: backup
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 2Gi
---
# Source: orientdb/templates/ingress.yaml


---
# Source: orientdb/templates/tests/simple-crud-test.yaml

