apiVersion: v1
kind: Service
metadata:
  labels:
    app: odoo
  name: odoo-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8069
      protocol: TCP
  selector:
    app: odoo
    tier: app