apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: odoo
  name: odoo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: docker.io/library/odoo:11.0
        imagePullPolicy: IfNotPresent
        env:
        - name: HOST
          value: db
        ports:
        - containerPort: 8069
        volumeMounts:
        - name: odoo-web-data-persistent
          mountPath: /var/lib/odoo
      volumes:
        - name: odoo-web-data-persistent
          persistentVolumeClaim:
            claimName: odoo-lib-volumeclaim
